package com.wj.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wj.greendao.User;
import com.wj.greendao.UserSon;
import com.wj.greendao.UserGoods;
import com.wj.greendao.TeacherBean;
import com.wj.greendao.StudentBean;
import com.wj.greendao.TeacherJoinStudentBean;

import com.wj.greendao.dao.UserDao;
import com.wj.greendao.dao.UserSonDao;
import com.wj.greendao.dao.UserGoodsDao;
import com.wj.greendao.dao.TeacherBeanDao;
import com.wj.greendao.dao.StudentBeanDao;
import com.wj.greendao.dao.TeacherJoinStudentBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig userSonDaoConfig;
    private final DaoConfig userGoodsDaoConfig;
    private final DaoConfig teacherBeanDaoConfig;
    private final DaoConfig studentBeanDaoConfig;
    private final DaoConfig teacherJoinStudentBeanDaoConfig;

    private final UserDao userDao;
    private final UserSonDao userSonDao;
    private final UserGoodsDao userGoodsDao;
    private final TeacherBeanDao teacherBeanDao;
    private final StudentBeanDao studentBeanDao;
    private final TeacherJoinStudentBeanDao teacherJoinStudentBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        userSonDaoConfig = daoConfigMap.get(UserSonDao.class).clone();
        userSonDaoConfig.initIdentityScope(type);

        userGoodsDaoConfig = daoConfigMap.get(UserGoodsDao.class).clone();
        userGoodsDaoConfig.initIdentityScope(type);

        teacherBeanDaoConfig = daoConfigMap.get(TeacherBeanDao.class).clone();
        teacherBeanDaoConfig.initIdentityScope(type);

        studentBeanDaoConfig = daoConfigMap.get(StudentBeanDao.class).clone();
        studentBeanDaoConfig.initIdentityScope(type);

        teacherJoinStudentBeanDaoConfig = daoConfigMap.get(TeacherJoinStudentBeanDao.class).clone();
        teacherJoinStudentBeanDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        userSonDao = new UserSonDao(userSonDaoConfig, this);
        userGoodsDao = new UserGoodsDao(userGoodsDaoConfig, this);
        teacherBeanDao = new TeacherBeanDao(teacherBeanDaoConfig, this);
        studentBeanDao = new StudentBeanDao(studentBeanDaoConfig, this);
        teacherJoinStudentBeanDao = new TeacherJoinStudentBeanDao(teacherJoinStudentBeanDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(UserSon.class, userSonDao);
        registerDao(UserGoods.class, userGoodsDao);
        registerDao(TeacherBean.class, teacherBeanDao);
        registerDao(StudentBean.class, studentBeanDao);
        registerDao(TeacherJoinStudentBean.class, teacherJoinStudentBeanDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        userSonDaoConfig.getIdentityScope().clear();
        userGoodsDaoConfig.getIdentityScope().clear();
        teacherBeanDaoConfig.getIdentityScope().clear();
        studentBeanDaoConfig.getIdentityScope().clear();
        teacherJoinStudentBeanDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public UserSonDao getUserSonDao() {
        return userSonDao;
    }

    public UserGoodsDao getUserGoodsDao() {
        return userGoodsDao;
    }

    public TeacherBeanDao getTeacherBeanDao() {
        return teacherBeanDao;
    }

    public StudentBeanDao getStudentBeanDao() {
        return studentBeanDao;
    }

    public TeacherJoinStudentBeanDao getTeacherJoinStudentBeanDao() {
        return teacherJoinStudentBeanDao;
    }

}
