package com.wj.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wj.greendao.User;
import com.wj.greendao.UserSon;
import com.wj.greendao.UserGoods;

import com.wj.greendao.dao.UserDao;
import com.wj.greendao.dao.UserSonDao;
import com.wj.greendao.dao.UserGoodsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig userSonDaoConfig;
    private final DaoConfig userGoodsDaoConfig;

    private final UserDao userDao;
    private final UserSonDao userSonDao;
    private final UserGoodsDao userGoodsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        userSonDaoConfig = daoConfigMap.get(UserSonDao.class).clone();
        userSonDaoConfig.initIdentityScope(type);

        userGoodsDaoConfig = daoConfigMap.get(UserGoodsDao.class).clone();
        userGoodsDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        userSonDao = new UserSonDao(userSonDaoConfig, this);
        userGoodsDao = new UserGoodsDao(userGoodsDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(UserSon.class, userSonDao);
        registerDao(UserGoods.class, userGoodsDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        userSonDaoConfig.getIdentityScope().clear();
        userGoodsDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public UserSonDao getUserSonDao() {
        return userSonDao;
    }

    public UserGoodsDao getUserGoodsDao() {
        return userGoodsDao;
    }

}
