package com.wj.greendao.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.wj.greendao.TeacherJoinStudentBean;

import com.wj.greendao.TeacherBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEACHER_BEAN".
*/
public class TeacherBeanDao extends AbstractDao<TeacherBean, Long> {

    public static final String TABLENAME = "TEACHER_BEAN";

    /**
     * Properties of entity TeacherBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Job = new Property(2, String.class, "job", false, "JOB");
    };

    private DaoSession daoSession;

    private Query<TeacherBean> studentBean_TeacherBeanListQuery;

    public TeacherBeanDao(DaoConfig config) {
        super(config);
    }
    
    public TeacherBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEACHER_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"JOB\" TEXT);"); // 2: job
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEACHER_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TeacherBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String job = entity.getJob();
        if (job != null) {
            stmt.bindString(3, job);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TeacherBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String job = entity.getJob();
        if (job != null) {
            stmt.bindString(3, job);
        }
    }

    @Override
    protected final void attachEntity(TeacherBean entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TeacherBean readEntity(Cursor cursor, int offset) {
        TeacherBean entity = new TeacherBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // job
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TeacherBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setJob(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TeacherBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TeacherBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "teacherBeanList" to-many relationship of StudentBean. */
    public List<TeacherBean> _queryStudentBean_TeacherBeanList(Long sId) {
        synchronized (this) {
            if (studentBean_TeacherBeanListQuery == null) {
                QueryBuilder<TeacherBean> queryBuilder = queryBuilder();
                queryBuilder.join(TeacherJoinStudentBean.class, TeacherJoinStudentBeanDao.Properties.TId)
                    .where(TeacherJoinStudentBeanDao.Properties.SId.eq(sId));
                studentBean_TeacherBeanListQuery = queryBuilder.build();
            }
        }
        Query<TeacherBean> query = studentBean_TeacherBeanListQuery.forCurrentThread();
        query.setParameter(0, sId);
        return query.list();
    }

}
