package com.wj.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.wj.greendao.UserSon;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_SON".
*/
public class UserSonDao extends AbstractDao<UserSon, Long> {

    public static final String TABLENAME = "USER_SON";

    /**
     * Properties of entity UserSon.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property SonId = new Property(0, Long.class, "sonId", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
    };


    public UserSonDao(DaoConfig config) {
        super(config);
    }
    
    public UserSonDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_SON\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: sonId
                "\"NAME\" TEXT);"); // 1: name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_SON\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserSon entity) {
        stmt.clearBindings();
 
        Long sonId = entity.getSonId();
        if (sonId != null) {
            stmt.bindLong(1, sonId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserSon entity) {
        stmt.clearBindings();
 
        Long sonId = entity.getSonId();
        if (sonId != null) {
            stmt.bindLong(1, sonId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UserSon readEntity(Cursor cursor, int offset) {
        UserSon entity = new UserSon( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // sonId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserSon entity, int offset) {
        entity.setSonId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserSon entity, long rowId) {
        entity.setSonId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserSon entity) {
        if(entity != null) {
            return entity.getSonId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
